name: product
custom_attributes:
  - name: name
    attribute_type: string
  - name: description
    attribute_type: text
  - name: sex
    attribute_type: string
  - name: price
    attribute_type: int
  - name: brand_id
    attribute_type: string
  - name: product_type_id
    attribute_type: string
